document.write("<table border = ”0” cellspacing = ”2” bgcolor = ”black” width = ”200”>");
document.write("<tr>");
document.write("<td>profundidad</td>");
document.write("<td>"+screen.colorDepth+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>altura</td>");
document.write("<td>"+screen.height+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>anchura</td>");
document.write("<td>"+screen.width+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>Orientacion</td>");
document.write("<td>"+screen.orientation+"</td>");
document.write("</tr>");
document.write("</table>");